language: java
jdk: 
    - oraclejdk8
      
before_install:
    - sudo apt-get update -qq
    - sudo apt-get install gcc make
script:
    - make

notifications:
  email:
    on_success: change
    on_failure: always
